# Generated by Django 4.2.16 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('gk', 'GK'), ('cb', 'CB'), ('cm', 'CM'), ('st', 'ST')], default='value1', max_length=15),
        ),
    ]
