# Generated by Django 4.2.16 on 2024-12-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('earth', models.CharField(choices=[('EU', 'Europe'), ('Eng', 'England'), ('ES', 'England')], default='none', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('CM', 'CM'), ('ST', 'ST')], default='none', max_length=15),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='general.league')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='general.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='general.league'),
        ),
    ]
