# Generated by Django 4.2.16 on 2024-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_league_alter_player_position_club_player_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='red_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='earth',
            field=models.CharField(choices=[('EU', 'Europe'), ('Eng', 'England'), ('ES', 'Spain')], default='none', max_length=15),
        ),
    ]
