# Generated by Django 4.2.16 on 2024-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_player_assits_player_games_player_goals_player_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
