# Generated by Django 4.2.16 on 2024-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_club_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America')], default='none', max_length=25)),
            ],
        ),
    ]
