# Generated by Django 4.2.16 on 2024-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_national'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(default=84.29166666666667, max_length=9)),
                ('is_national', models.BooleanField(default=False)),
            ],
        ),
    ]
